targets:
  $default:
    builders:
      semantic_gen:auto_tag_builder:
        generate_for:
          - lib/**.dart

builders:
  auto_tag_builder:
    import: "package:semantic_gen/src/builder.dart"
    builder_factories: ["autoTagBuilder"]
    build_extensions: {".dart": [".tagged.g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
